# Generated by Django 5.1.7 on 2025-04-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='justdialclinic',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='justdialdoctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nmcdoctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='practodoctor',
            options={'managed': False},
        ),
    ]
