# Generated by Django 5.1.7 on 2025-04-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpapp', '0002_alter_justdialclinic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='justdialclinic',
            table='Cpapp_justdial_clinic',
        ),
        migrations.AlterModelTable(
            name='justdialdoctor',
            table='Cpapp_justdial_doctor',
        ),
        migrations.AlterModelTable(
            name='nmcdoctor',
            table='Cpapp_nmc_doctor',
        ),
        migrations.AlterModelTable(
            name='practodoctor',
            table='Cpapp_practo_doctor',
        ),
    ]
