# Generated by Django 4.2.20 on 2025-04-25 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpapp', '0004_bajajdoctor_googlemapdata_nmcdentaldoctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPractoDoctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(blank=True)),
                ('doctor_name', models.TextField(blank=True)),
                ('qualification', models.TextField(blank=True)),
                ('specialization', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('verification_label', models.TextField(blank=True)),
                ('rating', models.TextField(blank=True)),
                ('rating_count', models.TextField(blank=True)),
                ('services', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('registration', models.TextField(blank=True)),
                ('associated_clinic_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Cpapp_new_practo_doctor',
                'managed': False,
            },
        ),
    ]
