from django.db import models
from django.utils import timezone


class GoogleMapData(models.Model):
    """Model for storing data scraped from Google Maps"""
    id = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(default=timezone.now)
    query = models.TextField(null=True, blank=True)
    name = models.TextField(null=True, blank=True)
    name_for_emails = models.TextField(null=True, blank=True)
    site = models.TextField(null=True, blank=True)
    site_company_insights_description = models.TextField(null=True, blank=True)
    site_company_insights_is_public = models.TextField(null=True, blank=True)
    site_company_insights_linkedin_bio = models.TextField(null=True, blank=True)
    site_company_insights_name = models.TextField(null=True, blank=True)
    site_company_insights_twitter_handle = models.TextField(null=True, blank=True)
    site_company_insights_address = models.TextField(null=True, blank=True)
    site_company_insights_city = models.TextField(null=True, blank=True)
    site_company_insights_country = models.TextField(null=True, blank=True)
    site_company_insights_employees = models.TextField(null=True, blank=True)
    site_company_insights_facebook_company_page = models.TextField(null=True, blank=True)
    site_company_insights_founded_year = models.TextField(null=True, blank=True)
    site_company_insights_linkedin_company_page = models.TextField(null=True, blank=True)
    site_company_insights_revenue = models.TextField(null=True, blank=True)
    site_company_insights_state = models.TextField(null=True, blank=True)
    site_company_insights_timezone = models.TextField(null=True, blank=True)
    site_company_insights_zip = models.TextField(null=True, blank=True)
    site_company_insights_industry = models.TextField(null=True, blank=True)
    site_company_insights_phone = models.TextField(null=True, blank=True)
    site_company_insights_total_money_raised = models.TextField(null=True, blank=True)
    category = models.TextField(null=True, blank=True)
    type = models.TextField(null=True, blank=True)
    phone = models.TextField(null=True, blank=True)
    full_address = models.TextField(null=True, blank=True)
    borough = models.TextField(null=True, blank=True)
    street = models.TextField(null=True, blank=True)
    city = models.TextField(null=True, blank=True)
    postal_code = models.TextField(null=True, blank=True)
    state = models.TextField(null=True, blank=True)
    country = models.TextField(null=True, blank=True)
    latitude = models.TextField(null=True, blank=True)
    longitude = models.TextField(null=True, blank=True)
    time_zone = models.TextField(null=True, blank=True)
    rating = models.TextField(null=True, blank=True)
    reviews = models.TextField(null=True, blank=True)
    reviews_link = models.TextField(null=True, blank=True)
    reviews_tags = models.TextField(null=True, blank=True)
    reviews_per_score = models.TextField(null=True, blank=True)
    reviews_per_score_1 = models.TextField(null=True, blank=True)
    reviews_per_score_2 = models.TextField(null=True, blank=True)
    reviews_per_score_3 = models.TextField(null=True, blank=True)
    reviews_per_score_4 = models.TextField(null=True, blank=True)
    reviews_per_score_5 = models.TextField(null=True, blank=True)
    business_status = models.TextField(null=True, blank=True)
    posts = models.TextField(null=True, blank=True)
    verified = models.TextField(null=True, blank=True)
    owner_id = models.TextField(null=True, blank=True)
    owner_title = models.TextField(null=True, blank=True)
    google_id = models.TextField(null=True, blank=True)
    reviews_id = models.TextField(null=True, blank=True)
    located_google_id = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name or str(self.id)

    class Meta:
        db_table = 'Cpapp_googlemap_data'
        managed = False
